---
#cluster_name: infra-clusters.kubeint.gl-poc.com
cluster_name: k8s-cluster.vdatacenter.com
state_store: s3://k8s-cluster.vdatacenter.com

# Remote access
ssh_public_key: /home/raven/setup/group_vars/all/id_rsa.pub

# Regions / Availability zones
aws_region: us-east-1
aws_zones: us-east-1a,us-east-1b,us-east-1c
# Use master_zones if you want your masters in different zones than worker nodes.
# Useful especially when you want 1 master in single zone but workers in several zones.
# When not defined, aws_zones will be sued instead
master_zones: us-east-1a,us-east-1b,us-east-1c

# Network
dns_zone: k8s-cluster.vdatacenter.com
network_cidr: 10.21.0.0/16
kubernetes_networking: weave
topology: private

# EC2 host sizing
master_size: t3.large
master_count: 3
master_volume_size: 20
node_size: t3.medium
node_count: 3
node_volume_size: 20
node_autoscaler_min: 1
node_autoscaler_max: 6

# Tags
tag_creator: kops-ansible
tag_owner: kops-devops
tag_billing: cluster
tag_environment: test

# Helm download repos:

helm_url: https://storage.googleapis.com/kubernetes-helm/helm-v2.7.1-linux-amd64.tar.gz
helm_folder: /usr/local/bin
